package ir.ayantech.pishkhansdk.constants

object Parameter {
    const val NationalCode = "NationalCode"
    const val MobileNumber = "MobileNumber"
    const val PlateNumber = "PlateNumber"
    const val LicenseNumber = "LicenseNumber"
    const val VIN = "VIN"
    const val Password = "Password"
    const val Username = "Username"
    const val AccountNumber = "AccountNumber"
    const val UniqueNumber = "UniqueNumber"
    const val Identifier = "Identifier"
    const val ParticipateCode = "ParticipateCode"
    const val LineNumber = "LineNumber"
    const val Operator = "Operator"
    const val Year = "Year"
    const val Month = "Month"
    const val YearOfBirth = "YearOfBirth"
    const val IdentificationCode = "IdentificationCode"
    const val ProductCode = "ProductCode"
    const val PurchaseKey = "PurchaseKey"
    const val Amount = "Amount"
    const val Barcode = "Barcode"
    const val EngineNumber = "EngineNumber"
    const val TaxGroup = "TaxGroup"
    const val DateOfBirth = "DateOfBirth"
    const val TrackingCode = "TrackingCode"
    const val ChequeNumber = "ChequeNumber"
    const val InsuranceUniqueCode = "InsuranceUniqueCode"
    const val AccountType = "AccountType"
    const val CardNumber = "CardNumber"
    const val Iban = "Iban"
    const val Bank = "Bank"
    const val CarBarCodeNumber = "CarBarCodeNumber"
    const val DocumentNumber = "DocumentNumber"
    const val IdentifierType = "IdentifierType"
    const val NationalCodeOwner = "NationalCodeOwner"
    const val NationalCodeBuyer = "NationalCodeBuyer"
    const val SimType = "SimType"
}